# NUMPY LEARNING

In [1]:
import numpy as ap

In [2]:
myarr= ap.array([[3,5,7,9],
                 [10,20,30,40]])   # Array value input

In [3]:
myarr[0,1]

5

In [4]:
myarr.shape      # For checking array dimension

(2, 4)

In [5]:
myarr.shape=(4,2)   #For changing array dimension

In [6]:
myarr.shape

(4, 2)

In [7]:
myarr

array([[ 3,  5],
       [ 7,  9],
       [10, 20],
       [30, 40]])

In [8]:
myarr.dtype    # For checking array typing

dtype('int64')

In [9]:
myarr[0,1]=45        #For changing array value

In [10]:
myarr

array([[ 3, 45],
       [ 7,  9],
       [10, 20],
       [30, 40]])

In [11]:
zeros =ap.zeros ((2,5))                # zeros method

In [12]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Full method

In [13]:
n=ap.full((3,3),22)

In [14]:
n

array([[22, 22, 22],
       [22, 22, 22],
       [22, 22, 22]])

## Joining NumPy Arrays

In [15]:
v1=ap.array([10,20,30])
v2=ap.array([40,50,60])

In [16]:
ap.vstack((v1,v2))    #vstack() method

array([[10, 20, 30],
       [40, 50, 60]])

In [17]:
ap.hstack((v1,v2))    #hstack() method

array([10, 20, 30, 40, 50, 60])

In [18]:
ap.column_stack((v1,v2))     #column_stack() method

array([[10, 40],
       [20, 50],
       [30, 60]])

## range method

In [19]:
rng = ap.arange(15)

In [20]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
rng1 = ap.arange(10,20)

In [22]:
rng1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [23]:
rng2 = ap.arange(10,50,5)

In [24]:
rng2

array([10, 15, 20, 25, 30, 35, 40, 45])

## random method

In [25]:
random = ap.random.randint(100,200)

In [26]:
random

188

In [27]:
random = ap.random.randint(1,100,5)

In [28]:
random

array([55,  2, 25, 90, 50])

In [29]:
lspace = ap.linspace(1,4,10)

In [30]:
lspace

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [31]:
n1=ap.full((2,2),10)

In [32]:
n1

array([[10, 10],
       [10, 10]])

## NumPy Array Mathematics

In [33]:
n1= ap.array([10,20,30])
n2=ap.array([40,50,60])

In [34]:
ap.sum([n1,n2], axis=0)

array([50, 70, 90])

In [35]:
ap.sum([n1,n2], axis=1)

array([ 60, 150])

In [36]:
ap.sum([n1,n2])         # sum two variables

210

In [37]:
n1=n1+1                  # Addition
n1                   

array([11, 21, 31])

In [38]:
n1=n1*2          #Multiplication
n1

array([22, 42, 62])

In [39]:
n1=n1-1            # Subtraction
n1

array([21, 41, 61])

In [40]:
n2=n2/2            #Division
n2

array([20., 25., 30.])

## NumPy Array Functions

In [41]:
n1=ap.array([10,20,30,40,50])
ap.mean(n1)

30.0

In [42]:
n1

array([10, 20, 30, 40, 50])

In [43]:
ap.std(n1)

14.142135623730951

In [44]:
ap.median(n1)

30.0

## NumPy intersection & Diff

In [45]:
v1=ap.array([10,20,30,40,50])
v2=ap.array([40,50,60,70,80])

In [46]:
ap.intersect1d(v1,v2)  # chcek same values

array([40, 50])

In [47]:
ap.setdiff1d(v1,v2)   # check diff value (v1-v2)

array([10, 20, 30])

In [48]:
ap.setdiff1d(v2,v1)   # check diff value (v2-v1)

array([60, 70, 80])

## NumPy save & load

In [49]:
x1=ap.array([10,20,30,40,50,60])

In [50]:
ap.save('my_num',x1)

In [51]:
x2=ap.load('my_num.npy')
x2

array([10, 20, 30, 40, 50, 60])